version: '3'
services:
  redis:
    image: redis
  db:
    image: postgres:9.4
  vote:
    build: ./vote
    ports:
      - 5000:80
  worker:
    build: ./worker 
  result:
    build: ./result
    ports:
      - 5001:80    