version: '3'
services:
  redis:
    image: redis
  db:
    image: postgres:9.4
  vote:
    build: ./vote
    ports:
      - 5000:80
    links:
      - redis
  worker:
    build: ./worker
    links:
     - db
     - redis
  result:
    build: ./result
    ports:
      - 5001:80
    links:
      - db